"""
Django settings for hairbnb_backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5z0had1txu1r8p2fdqjh5#c12zmws%32!1o-ttuxd0)+)82c-s'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = os.getenv('DEBUG', 'False') == 'True'


#ALLOWED_HOSTS = ['192.168.0.202', '127.0.0.1', 'localhost']
# ALLOWED_HOSTS = [
#     '127.0.0.1',
#     'localhost',
#     '192.168.0.248',  # Ton IP locale
#     '192.168.0.248',
#     '91.86.52.162',    # Ton IP publique
#     'hairbnb.site',
#     'www.hairbnb.site',
#     'api.hairbnb.site',
#     "https://hairbnb.site",
#     "https://www.hairbnb.site",
#
# ]

ALLOWED_HOSTS = ['hairbnb.site', 'www.hairbnb.site']

#STATIC_URL = '/static/'
MEDIA_URL = '/media/'

#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# STATIC_URL = '/static/'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 📂 Définir où stocker les fichiers statiques collectés
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 📂 Facultatif : Ajouter un dossier où tu mets tes fichiers statiques manuellement
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "sk_test_51QxTcwPLEsfXjeyf4PAmUsqK9XGI6G1WG5a7sfE34yfIs2TyBaNkv9DndcodbC7jQxWxgDS7Jobx20eADkzeEyQj00OWORrF13")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "pk_test_51QxTcwPLEsfXjeyfbxYM0qSVUfouAqtUGbVOTXmf3fr3y6tBtX5aylUzP3xLPniIXWu7hmuBGdvIWJ6fueZZe70d00dn2sPdfv")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET","whsec_Q10G900SvmGxCqmaU641SC8T3MAvbJFo")



# Configuration des emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.hairbnb.site'
EMAIL_PORT = 465  # Port SSL
EMAIL_USE_SSL = True  # Utiliser SSL au lieu de TLS
EMAIL_HOST_USER = 'noreply@hairbnb.site'
EMAIL_HOST_PASSWORD = '**Time1990**'  # À définir dans les variables d'environnement pour la sécurité
DEFAULT_FROM_EMAIL = 'HairBnB <noreply@hairbnb.site>'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Assurez-vous que cette ligne est présente
        'APP_DIRS': True,  # Ceci doit être True pour que Django cherche dans les dossiers templates des applications
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hairbnb.apps.HairbnbConfig',
    'corsheaders',
    'rest_framework',

]

MIDDLEWARE = [
    'hairbnb_backend.middlewares.BlockWordPressScannersMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middleware.country_restriction.CountryRestrictionMiddleware',
    'middleware.firebase_auth_middleware.FirebaseAuthMiddleware',
    'middleware.bypass_csrf_middleware.BypassCSRFMiddleware',
    'middleware.block_malicious_requests_middleware.BlockMaliciousRequestsMiddleware',
]




# Nombre d'échecs consécutifs avant de bloquer l'accès (par IP)
AXES_FAILURE_LIMIT = 5

# Temps d'attente avant de débloquer l'accès (en heures)
AXES_COOLOFF_TIME = 1

# Fonction utilisée pour stocker les échecs de connexion
# Ici, on utilise la base de données pour stocker les échecs
AXES_LOCKOUT_CALLABLE = 'axes.handlers.database.AxesDatabaseHandler'

# Si l'utilisateur se connecte correctement après un blocage, remettre à zéro le compteur d'échecs
AXES_RESET_ON_SUCCESS = True


# Chemin vers le fichier de configuration Firebase
FIREBASE_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'firebase_auth_services/firebase_credentials.json')



ROOT_URLCONF = 'hairbnb_backend.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         #'DIRS': [BASE_DIR / 'templates']
#         'DIRS': [os.path.join(BASE_DIR, 'templates')]
#         ,
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

WSGI_APPLICATION = 'hairbnb_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# ✅ Ligne pour forcer l'encodage en UTF-8
DEFAULT_CHARSET = 'utf-8'
FILE_CHARSET = 'utf-8'

DATABASES = {
    'default': {
         'ENGINE': 'django.db.backends.postgresql',
        #'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'dbhairbnb',
        'USER': 'postgres',
        'PASSWORD': 'Soul2003',
        'HOST': 'localhost',
        'PORT': '5432',
        'OPTIONS': {
            'client_encoding': 'UTF8',
        },
    }
}

# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.environ.get("DATABASE_URL"),
#         conn_max_age=600,
#         ssl_require=True
#     )
# }

ANTHROPIC_API_KEY = "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"





# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    # "http://localhost:3000",
    # "http://localhost:50734",
    "http://127.0.0.1:8080",
    "http://hairbnb.site",
    "http://www.hairbnb.site",
    "http://api.hairbnb.site",
    "http://91.86.53.160:8080",
    "http://91.86.53.160"
]

CSRF_TRUSTED_ORIGINS = ["https://www.hairbnb.site","https://hairbnb.site","http://localhost:53655",]
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True


CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS"
]

CORS_ALLOW_HEADERS = [  # Autoriser les en-têtes courants
    "Authorization",
    "Content-Type",
    "X-CSRFToken",
]



# import os
#
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#
#     'formatters': {
#         'verbose': {
#             'format': '[{asctime}] {levelname} {name} — {message}',
#             'style': '{',
#         },
#         'geoip': {
#             'format': '[%(asctime)s] [%(levelname)s] [%(ip)s] %(message)s',
#         },
#     },
#
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#             'formatter': 'verbose',
#         },
#         'geoip_file': {
#             'level': 'INFO',
#             'class': 'logging.FileHandler',
#             'filename': os.path.join(BASE_DIR, 'logs', 'geoip_blocked.log'),
#             'formatter': 'geoip',
#         },
#     },
#
#     'loggers': {
#         'django': {
#             'handlers': ['console'],
#             'level': 'DEBUG',  # 🔥 Tu peux remettre à INFO en production
#             'propagate': True,
#         },
#         'geoip_blocker': {
#             'handlers': ['geoip_file'],
#             'level': 'INFO',
#             'propagate': False,
#         },
#         '__main__': {  # Pour les erreurs dans tes fichiers comme email_views.py
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#     },
# }


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'geoip': {
            'format': '[%(asctime)s] [%(levelname)s] [%(ip)s] %(message)s',
        },
    },
    'handlers': {
        'geoip_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'geoip_blocked.log'),
            'formatter': 'geoip',
        },
    },
    'loggers': {
        'geoip_blocker': {
            'handlers': ['geoip_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}