# Generated by Django 5.1.4 on 2024-12-26 01:19

import django.db.models.deletion
import hairbnb.services.upload_services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblCoiffeuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination_sociale', models.CharField(blank=True, max_length=255, null=True)),
                ('tva', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Coiffeuse',
                'verbose_name_plural': 'Coiffeuses',
            },
        ),
        migrations.CreateModel(
            name='TblLocalite',
            fields=[
                ('idTblLocalite', models.AutoField(primary_key=True, serialize=False)),
                ('commune', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TblPrix',
            fields=[
                ('idTblPrix', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TblTemps',
            fields=[
                ('idTblTemps', models.AutoField(primary_key=True, serialize=False)),
                ('minutes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TblRue',
            fields=[
                ('idTblRue', models.AutoField(primary_key=True, serialize=False)),
                ('nom_rue', models.CharField(max_length=255)),
                ('localite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rues', to='hairbnb.tbllocalite')),
            ],
            options={
                'unique_together': {('nom_rue', 'localite')},
            },
        ),
        migrations.CreateModel(
            name='TblAdresse',
            fields=[
                ('idTblAdresse', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10)),
                ('boite_postale', models.CharField(blank=True, max_length=10, null=True)),
                ('rue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='hairbnb.tblrue')),
            ],
        ),
        migrations.CreateModel(
            name='TblSalon',
            fields=[
                ('idTblSalon', models.AutoField(primary_key=True, serialize=False)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_salon', models.ImageField(blank=True, default='photos/defaults/logo_default.png', null=True, upload_to='photos/logos/')),
                ('coiffeuse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salon', to='hairbnb.tblcoiffeuse')),
            ],
        ),
        migrations.CreateModel(
            name='TblImageSalon',
            fields=[
                ('idTblImageSalon', models.AutoField(primary_key=True, serialize=False)),
                ('urlImages', models.ImageField(upload_to=hairbnb.services.upload_services.salon_image_upload_to)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hairbnb.tblsalon')),
            ],
        ),
        migrations.CreateModel(
            name='TblServices',
            fields=[
                ('idTblServices', models.AutoField(primary_key=True, serialize=False)),
                ('intitule_service', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hairbnb.tblprix')),
                ('temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hairbnb.tbltemps')),
            ],
        ),
        migrations.CreateModel(
            name='TblSalonServices',
            fields=[
                ('idSalonService', models.AutoField(primary_key=True, serialize=False)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_services', to='hairbnb.tblsalon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_services', to='hairbnb.tblservices')),
            ],
            options={
                'unique_together': {('salon', 'service')},
            },
        ),
        migrations.AddField(
            model_name='tblsalon',
            name='services',
            field=models.ManyToManyField(related_name='salons', through='hairbnb.TblSalonServices', to='hairbnb.tblservices'),
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('idTblUser', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(choices=[('coiffeuse', 'Coiffeuse'), ('client', 'Client')], max_length=10)),
                ('sexe', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme'), ('autre', 'Autre')], max_length=6)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photo_profil', models.ImageField(blank=True, default='photos/defaults/avatar.png', null=True, upload_to='photos/profils/')),
                ('adresse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='hairbnb.tbladresse')),
            ],
        ),
        migrations.AddField(
            model_name='tblcoiffeuse',
            name='idTblUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coiffeuse', to='hairbnb.tbluser'),
        ),
        migrations.CreateModel(
            name='TblClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTblUser', models.ForeignKey(db_column='idTblUser', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='hairbnb.tbluser')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
