# Generated by Django 5.1.4 on 2024-12-26 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblservices',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='tblservices',
            name='temps',
        ),
        migrations.CreateModel(
            name='TblService',
            fields=[
                ('idTblService', models.AutoField(primary_key=True, serialize=False)),
                ('intitule_service', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='hairbnb.tblprix')),
                ('temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='hairbnb.tbltemps')),
            ],
        ),
        migrations.CreateModel(
            name='TblSalonService',
            fields=[
                ('idSalonService', models.AutoField(primary_key=True, serialize=False)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_service', to='hairbnb.tblsalon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_service', to='hairbnb.tblservice')),
            ],
            options={
                'unique_together': {('salon', 'service')},
            },
        ),
        migrations.AlterField(
            model_name='tblsalon',
            name='services',
            field=models.ManyToManyField(related_name='salons', through='hairbnb.TblSalonService', to='hairbnb.tblservice'),
        ),
        migrations.DeleteModel(
            name='TblSalonServices',
        ),
        migrations.DeleteModel(
            name='TblServices',
        ),
    ]
