# Generated by Django 5.1.4 on 2024-12-27 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0002_remove_tblservices_prix_remove_tblservices_temps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblservice',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='tblservice',
            name='temps',
        ),
        migrations.CreateModel(
            name='TblServicePrix',
            fields=[
                ('idServicePrix', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_services', to='hairbnb.tblprix')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prix', to='hairbnb.tblservice')),
            ],
            options={
                'unique_together': {('service', 'prix')},
            },
        ),
        migrations.CreateModel(
            name='TblServiceTemps',
            fields=[
                ('idServiceTemps', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_temps', to='hairbnb.tblservice')),
                ('temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temps_services', to='hairbnb.tbltemps')),
            ],
            options={
                'unique_together': {('service', 'temps')},
            },
        ),
    ]
