# Generated by Django 5.1.4 on 2025-01-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0003_remove_tblservice_prix_remove_tblservice_temps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblprix',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tbltemps',
            name='idTblTemps',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
