# Generated by Django 5.1.4 on 2025-01-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0004_alter_tblprix_prix_alter_tbltemps_idtbltemps'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tblserviceprix',
            unique_together={('service',)},
        ),
    ]
