# Generated by Django 5.1.4 on 2025-02-04 20:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0005_alter_tblserviceprix_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblCart',
            fields=[
                ('idTblCart', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='hairbnb.tbluser')),
            ],
        ),
        migrations.CreateModel(
            name='TblPromotion',
            fields=[
                ('idPromotion', models.AutoField(primary_key=True, serialize=False)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='hairbnb.tblservice')),
            ],
        ),
        migrations.CreateModel(
            name='TblCartItem',
            fields=[
                ('idTblCartItem', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hairbnb.tblcart')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='hairbnb.tblservice')),
            ],
            options={
                'unique_together': {('cart', 'service')},
            },
        ),
    ]
