# Generated by Django 5.1.4 on 2025-02-08 14:24

import django.template.defaulttags
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0006_tblcart_tblpromotion_tblcartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpromotion',
            name='start_date',
            field=models.DateTimeField(default=django.template.defaulttags.now),
        ),
    ]
