# Generated by Django 5.1.4 on 2025-02-08 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0007_alter_tblpromotion_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpromotion',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
