# Generated by Django 5.1.4 on 2025-02-16 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0008_alter_tblpromotion_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblRendezVous',
            fields=[
                ('idRendezVous', models.AutoField(primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField()),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('confirmé', 'Confirmé'), ('annulé', 'Annulé'), ('terminé', 'Terminé')], default='en attente', max_length=20)),
                ('total_prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='hairbnb.tblclient')),
                ('coiffeuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='hairbnb.tblcoiffeuse')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='hairbnb.tblsalon')),
            ],
        ),
        migrations.CreateModel(
            name='TblPaiement',
            fields=[
                ('idPaiement', models.AutoField(primary_key=True, serialize=False)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('methode', models.CharField(choices=[('carte', 'Carte'), ('cash', 'Cash'), ('paypal', 'PayPal')], default='carte', max_length=20)),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('payé', 'Payé'), ('remboursé', 'Remboursé')], default='en attente', max_length=20)),
                ('rendez_vous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='hairbnb.tblrendezvous')),
            ],
        ),
        migrations.CreateModel(
            name='TblRendezVousService',
            fields=[
                ('idRendezVousService', models.AutoField(primary_key=True, serialize=False)),
                ('prix_applique', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duree_estimee', models.PositiveIntegerField(blank=True, null=True)),
                ('rendez_vous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_services', to='hairbnb.tblrendezvous')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_services', to='hairbnb.tblservice')),
            ],
            options={
                'unique_together': {('rendez_vous', 'service')},
            },
        ),
    ]
