# Generated by Django 5.1.4 on 2025-02-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0009_tblrendezvous_tblpaiement_tblrendezvousservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblrendezvous',
            name='duree_totale',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
