# Generated by Django 5.1.4 on 2025-03-22 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0010_tblrendezvous_duree_totale'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblIndisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('coiffeuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilites', to='hairbnb.tblcoiffeuse')),
            ],
        ),
        migrations.CreateModel(
            name='TblHoraireSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='hairbnb.tblsalon')),
            ],
            options={
                'unique_together': {('salon', 'jour')},
            },
        ),
    ]
