# Generated by Django 5.1.4 on 2025-03-23 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0011_tblindisponibilite_tblhorairesalon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblHoraireCoiffeuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('coiffeuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='hairbnb.tblcoiffeuse')),
            ],
            options={
                'unique_together': {('coiffeuse', 'jour')},
            },
        ),
        migrations.DeleteModel(
            name='TblHoraireSalon',
        ),
    ]
