# Generated by Django 5.1.4 on 2025-04-11 22:17

import django.db.models.deletion
import hairbnb.services.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0013_tblrendezvous_est_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblsalon',
            name='services',
        ),
        migrations.AddField(
            model_name='tblsalon',
            name='nom_salon',
            field=models.CharField(default='Salon temporaire', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblsalon',
            name='logo_salon',
            field=models.ImageField(default='photos/defaults/logo_default.png', upload_to='photos/logos/'),
        ),
        migrations.AlterField(
            model_name='tblsalon',
            name='slogan',
            field=models.CharField(default='Salon temporaire', max_length=75),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TblAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')])),
                ('commentaire', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hairbnb.tblclient')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='hairbnb.tblsalon')),
            ],
        ),
        migrations.CreateModel(
            name='TblSalonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/salon/', validators=[hairbnb.services.validators.validate_max_images])),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hairbnb.tblsalon')),
            ],
        ),
        migrations.DeleteModel(
            name='TblImageSalon',
        ),
    ]
