# Generated by Django 5.1.4 on 2025-04-13 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0017_alter_tblsalonimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblservice',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(600)]),
        ),
        migrations.AlterField(
            model_name='tblservice',
            name='intitule_service',
            field=models.CharField(max_length=100),
        ),
    ]
