# Generated by Django 5.1.4 on 2025-04-13 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0018_alter_tblservice_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblserviceprix',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
