# Generated by Django 5.1.4 on 2025-04-13 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0019_alter_tblserviceprix_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblserviceprix',
            name='prix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_services', to='hairbnb.tblprix'),
        ),
    ]
