# Generated by Django 5.1.4 on 2025-04-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0022_alter_tblprix_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsalon',
            name='a_propos',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='tblsalon',
            name='slogan',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
