# Generated by Django 5.1.4 on 2025-04-19 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0023_tblsalon_a_propos_alter_tblsalon_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblFavorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='hairbnb.tblsalon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='hairbnb.tbluser')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'unique_together': {('user', 'salon')},
            },
        ),
    ]
