# Generated by Django 5.1.4 on 2025-04-19 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0024_tblfavorite'),
    ]

    operations = [
    ]
