# Generated by Django 5.1.4 on 2025-04-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0025_auto_20250419_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblfavorite',
            old_name='id',
            new_name='idTblFavorite',
        ),
    ]
