# Generated by Django 5.1.4 on 2025-04-23 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0026_rename_id_tblfavorite_idtblfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('paiement', 'Paiement'), ('remboursement', 'Remboursement')], max_length=13)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('effectué', 'Effectué'), ('en attente', 'En attente')], max_length=20)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='hairbnb.tblpaiement')),
            ],
        ),
    ]
