# Generated by Django 5.1.4 on 2025-04-23 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0027_tbltransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblMethodePaiement',
            fields=[
                ('idTblMethodePaiement', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TblPaiementStatut',
            fields=[
                ('idTblPaiementStatut', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='tblpaiement',
            old_name='idPaiement',
            new_name='idTblPaiement',
        ),
        migrations.AddField(
            model_name='tblpaiement',
            name='email_client',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tblpaiement',
            name='receipt_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tblpaiement',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tblpaiement',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblpaiement',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tblpaiement',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tblpaiement',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hairbnb.tbluser'),
        ),
        migrations.AlterField(
            model_name='tblpaiement',
            name='rendez_vous',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairbnb.tblrendezvous'),
        ),
        migrations.AlterField(
            model_name='tblpaiement',
            name='methode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hairbnb.tblmethodepaiement'),
        ),
        migrations.AlterField(
            model_name='tblpaiement',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hairbnb.tblpaiementstatut'),
        ),
    ]
