# Generated by Django 5.1.4 on 2025-05-01 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0028_tblmethodepaiement_tblpaiementstatut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblEmailStatus',
            fields=[
                ('idTblEmailStatus', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TblEmailType',
            fields=[
                ('idTblEmailType', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TblEmailNotification',
            fields=[
                ('idTblEmailNotification', models.AutoField(primary_key=True, serialize=False)),
                ('sujet', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('tentatives', models.PositiveSmallIntegerField(default=0)),
                ('email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_recus', to='hairbnb.tbluser')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails_notification', to='hairbnb.tblrendezvous')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails_envoyes', to='hairbnb.tblsalon')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='hairbnb.tblemailstatus')),
                ('type_email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='hairbnb.tblemailtype')),
            ],
            options={
                'verbose_name': 'Notification par email',
                'verbose_name_plural': 'Notifications par email',
                'db_table': 'TblEmailNotification',
                'ordering': ['-date_creation'],
            },
        ),
    ]
