# Generated by Django 5.1.4 on 2025-05-08 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0030_aiconversation_aimessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblRole',
            fields=[
                ('idTblRole', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tbluser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='hairbnb.tblrole'),
        ),
    ]
