# Generated by Django 5.1.4 on 2025-05-08 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0031_tblrole_tbluser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='role',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='hairbnb.tblrole'),
        ),
    ]
