# Generated by Django 5.1.4 on 2025-05-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairbnb', '0032_alter_tbluser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimessage',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='AIConversation',
        ),
        migrations.DeleteModel(
            name='AIMessage',
        ),
    ]
